name: Basic / Deno Deploy

on:
  push:
    branches: [main]


jobs:
  deploy:
    name: Basic / Deno Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/basic
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 1.25.1

      - name: Build site
        run: deno run -A ./build.ts

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: ultra
          entrypoint: server.js
          root: examples/basic/.ultra
          import-map: importMap.server.json